SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "587"
SMTP_USER = "muhammadsamdani11@gmail.com"
SMTP_PASSWORD = "przcstvntpmpdjvf"
SMTP_FROM = "muhammadsamdani11@gmail.com"

MOVIEFLIX_RESET_SECRET = "movieflix-reset-secret-key-2026"